export default {
	CART_ADD: 'CART_ADD',
	CART_REMOVE: 'CART_REMOVE',
	CART_VISIBLE: 'CART_VISIBLE',
	CART_ENABLED: 'CART_ENABLED',
	SET_SELECTED: 'SET_SELECTED',
	RECEIVE_DATA: 'RECEIVE_DATA',
	RECEIVE_FORM: 'RECEIVE_FORM',
	RECEIVE_CHECK: 'RECEIVE_CHECK'
}