export default {
    CART_INIT: 'CART_INIT',
	CART_ADD: 'CART_ADD',
	CART_REMOVE: 'CART_REMOVE',
	CART_CLEAR: 'CART_CLEAR',
	CART_VISIBLE: 'CART_VISIBLE',
	CART_ENABLED: 'CART_ENABLED',
	SET_SELECTED: 'SET_SELECTED'
}
