export default {
	RECEIVE_ALL_NEWSLETTER: 'RECEIVE_ALL_NEWSLETTER',
	RECEIVE_NEWSLETTER: 'RECEIVE_NEWSLETTER',
	NEWSLETTER_CREATED: 'NEWSLETTER_CREATED',
	NEWSLETTER_UNSUBSCRIBE: 'NEWSLETTER_UNSUBSCRIBE'
}