export default {
	RECEIVE_ALL_ORDERS: 'RECEIVE_ALL_ORDERS',
	RECEIVE_PAID_ORDERS: 'RECEIVE_PAID_ORDERS',
	RECEIVE_DELIVERED_ORDERS: 'RECEIVE_DELIVERED_ORDERS',
	RECEIVE_ORDER: 'RECEIVE_ORDER',
	STATE_UPDATED: 'STATE_UPDATED',
	CREATED: 'CREATED',
    SET_PAYMENT_FORM: 'SET_PAYMENT_FORM'
}
